--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0 (Debian 16.0-1.pgdg120+1)
-- Dumped by pg_dump version 16.0 (Debian 16.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: coboss; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA coboss;


ALTER SCHEMA coboss OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: BusinnessTaskComments; Type: TABLE; Schema: coboss; Owner: postgres
--

CREATE TABLE coboss."BusinnessTaskComments" (
    "Id" integer NOT NULL,
    "Text" text NOT NULL,
    "Date" timestamp without time zone DEFAULT '2024-02-01 20:42:31.598911'::timestamp without time zone NOT NULL,
    "UserId" integer NOT NULL,
    "TaskId" integer NOT NULL
);


ALTER TABLE coboss."BusinnessTaskComments" OWNER TO postgres;

--
-- Name: BusinnessTaskComments_Id_seq; Type: SEQUENCE; Schema: coboss; Owner: postgres
--

ALTER TABLE coboss."BusinnessTaskComments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME coboss."BusinnessTaskComments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: BusinnessTaskRealisations; Type: TABLE; Schema: coboss; Owner: postgres
--

CREATE TABLE coboss."BusinnessTaskRealisations" (
    "Id" integer NOT NULL,
    "Date" timestamp without time zone DEFAULT '2024-02-01 20:42:31.599323'::timestamp without time zone NOT NULL,
    "TimeSpan" interval DEFAULT '00:00:00'::interval NOT NULL,
    "Description" text,
    "TaskId" integer NOT NULL,
    "EmployeeId" integer NOT NULL
);


ALTER TABLE coboss."BusinnessTaskRealisations" OWNER TO postgres;

--
-- Name: BusinnessTaskRealisations_Id_seq; Type: SEQUENCE; Schema: coboss; Owner: postgres
--

ALTER TABLE coboss."BusinnessTaskRealisations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME coboss."BusinnessTaskRealisations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: BusinnessTasks; Type: TABLE; Schema: coboss; Owner: postgres
--

CREATE TABLE coboss."BusinnessTasks" (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" text NOT NULL,
    "Date" timestamp without time zone DEFAULT '2024-02-01 20:42:31.599053'::timestamp without time zone NOT NULL,
    "Term" timestamp without time zone DEFAULT '2024-02-01 20:42:31.599072'::timestamp without time zone NOT NULL,
    "ProjectId" integer NOT NULL
);


ALTER TABLE coboss."BusinnessTasks" OWNER TO postgres;

--
-- Name: BusinnessTasksUsers; Type: TABLE; Schema: coboss; Owner: postgres
--

CREATE TABLE coboss."BusinnessTasksUsers" (
    "BusinnessTaskId" integer NOT NULL,
    "EmployeeId" integer NOT NULL
);


ALTER TABLE coboss."BusinnessTasksUsers" OWNER TO postgres;

--
-- Name: BusinnessTasks_Id_seq; Type: SEQUENCE; Schema: coboss; Owner: postgres
--

ALTER TABLE coboss."BusinnessTasks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME coboss."BusinnessTasks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: EmployeeHistories; Type: TABLE; Schema: coboss; Owner: postgres
--

CREATE TABLE coboss."EmployeeHistories" (
    "Id" integer NOT NULL,
    "DateFrom" timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    "DateTo" timestamp without time zone DEFAULT '9999-12-31 23:59:59.999999'::timestamp without time zone NOT NULL,
    "CostHourOfWork" numeric NOT NULL,
    "EmployeeId" integer NOT NULL
);


ALTER TABLE coboss."EmployeeHistories" OWNER TO postgres;

--
-- Name: EmployeeHistories_Id_seq; Type: SEQUENCE; Schema: coboss; Owner: postgres
--

ALTER TABLE coboss."EmployeeHistories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME coboss."EmployeeHistories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Employees; Type: TABLE; Schema: coboss; Owner: postgres
--

CREATE TABLE coboss."Employees" (
    "Id" integer NOT NULL,
    "Code" character varying(50) NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Surname" character varying(100) NOT NULL,
    "PESEL" text,
    "NIP" text,
    "DateOfBirth" timestamp without time zone NOT NULL
);


ALTER TABLE coboss."Employees" OWNER TO postgres;

--
-- Name: Employees_Id_seq; Type: SEQUENCE; Schema: coboss; Owner: postgres
--

ALTER TABLE coboss."Employees" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME coboss."Employees_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: GlobalSettings; Type: TABLE; Schema: coboss; Owner: postgres
--

CREATE TABLE coboss."GlobalSettings" (
    "Id" integer NOT NULL,
    "Key" integer NOT NULL,
    "Value" text NOT NULL,
    "Type" integer NOT NULL
);


ALTER TABLE coboss."GlobalSettings" OWNER TO postgres;

--
-- Name: GlobalSettings_Id_seq; Type: SEQUENCE; Schema: coboss; Owner: postgres
--

ALTER TABLE coboss."GlobalSettings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME coboss."GlobalSettings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ObjectCodes; Type: TABLE; Schema: coboss; Owner: postgres
--

CREATE TABLE coboss."ObjectCodes" (
    "Id" integer NOT NULL,
    "EntityName" text NOT NULL,
    "CodeNumber" integer NOT NULL,
    "CodeLength" integer DEFAULT 10 NOT NULL
);


ALTER TABLE coboss."ObjectCodes" OWNER TO postgres;

--
-- Name: ObjectCodes_Id_seq; Type: SEQUENCE; Schema: coboss; Owner: postgres
--

ALTER TABLE coboss."ObjectCodes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME coboss."ObjectCodes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Projects; Type: TABLE; Schema: coboss; Owner: postgres
--

CREATE TABLE coboss."Projects" (
    "Id" integer NOT NULL,
    "Number" text NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" text NOT NULL,
    "Term" timestamp without time zone DEFAULT '2024-02-01 20:42:31.600362'::timestamp without time zone NOT NULL,
    "ManagerId" integer NOT NULL
);


ALTER TABLE coboss."Projects" OWNER TO postgres;

--
-- Name: Projects_Id_seq; Type: SEQUENCE; Schema: coboss; Owner: postgres
--

ALTER TABLE coboss."Projects" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME coboss."Projects_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RefreshTokensData; Type: TABLE; Schema: coboss; Owner: postgres
--

CREATE TABLE coboss."RefreshTokensData" (
    "Id" integer NOT NULL,
    "Token" character varying(88) NOT NULL,
    "JwtId" text NOT NULL,
    "CreationDate" timestamp without time zone DEFAULT '2024-02-01 20:42:31.600587'::timestamp without time zone NOT NULL,
    "ExpiryDate" timestamp without time zone NOT NULL,
    "Used" boolean NOT NULL,
    "UserId" integer NOT NULL
);


ALTER TABLE coboss."RefreshTokensData" OWNER TO postgres;

--
-- Name: RefreshTokensData_Id_seq; Type: SEQUENCE; Schema: coboss; Owner: postgres
--

ALTER TABLE coboss."RefreshTokensData" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME coboss."RefreshTokensData_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Roles; Type: TABLE; Schema: coboss; Owner: postgres
--

CREATE TABLE coboss."Roles" (
    "Id" integer NOT NULL,
    "Name" character varying(50) NOT NULL
);


ALTER TABLE coboss."Roles" OWNER TO postgres;

--
-- Name: Roles_Id_seq; Type: SEQUENCE; Schema: coboss; Owner: postgres
--

ALTER TABLE coboss."Roles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME coboss."Roles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: coboss; Owner: postgres
--

CREATE TABLE coboss."Users" (
    "Id" integer NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Password" character varying(255) NOT NULL,
    "Salt" bytea NOT NULL,
    "EmployeeId" integer,
    "RoleId" integer NOT NULL
);


ALTER TABLE coboss."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: coboss; Owner: postgres
--

ALTER TABLE coboss."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME coboss."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: coboss; Owner: postgres
--

CREATE TABLE coboss."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE coboss."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: BusinnessTaskComments; Type: TABLE DATA; Schema: coboss; Owner: postgres
--

COPY coboss."BusinnessTaskComments" ("Id", "Text", "Date", "UserId", "TaskId") FROM stdin;
\.


--
-- Data for Name: BusinnessTaskRealisations; Type: TABLE DATA; Schema: coboss; Owner: postgres
--

COPY coboss."BusinnessTaskRealisations" ("Id", "Date", "TimeSpan", "Description", "TaskId", "EmployeeId") FROM stdin;
\.


--
-- Data for Name: BusinnessTasks; Type: TABLE DATA; Schema: coboss; Owner: postgres
--

COPY coboss."BusinnessTasks" ("Id", "Name", "Description", "Date", "Term", "ProjectId") FROM stdin;
\.


--
-- Data for Name: BusinnessTasksUsers; Type: TABLE DATA; Schema: coboss; Owner: postgres
--

COPY coboss."BusinnessTasksUsers" ("BusinnessTaskId", "EmployeeId") FROM stdin;
\.


--
-- Data for Name: EmployeeHistories; Type: TABLE DATA; Schema: coboss; Owner: postgres
--

COPY coboss."EmployeeHistories" ("Id", "DateFrom", "DateTo", "CostHourOfWork", "EmployeeId") FROM stdin;
\.


--
-- Data for Name: Employees; Type: TABLE DATA; Schema: coboss; Owner: postgres
--

COPY coboss."Employees" ("Id", "Code", "Name", "Surname", "PESEL", "NIP", "DateOfBirth") FROM stdin;
\.


--
-- Data for Name: GlobalSettings; Type: TABLE DATA; Schema: coboss; Owner: postgres
--

COPY coboss."GlobalSettings" ("Id", "Key", "Value", "Type") FROM stdin;
\.


--
-- Data for Name: ObjectCodes; Type: TABLE DATA; Schema: coboss; Owner: postgres
--

COPY coboss."ObjectCodes" ("Id", "EntityName", "CodeNumber", "CodeLength") FROM stdin;
\.


--
-- Data for Name: Projects; Type: TABLE DATA; Schema: coboss; Owner: postgres
--

COPY coboss."Projects" ("Id", "Number", "Name", "Description", "Term", "ManagerId") FROM stdin;
\.


--
-- Data for Name: RefreshTokensData; Type: TABLE DATA; Schema: coboss; Owner: postgres
--

COPY coboss."RefreshTokensData" ("Id", "Token", "JwtId", "CreationDate", "ExpiryDate", "Used", "UserId") FROM stdin;
\.


--
-- Data for Name: Roles; Type: TABLE DATA; Schema: coboss; Owner: postgres
--

COPY coboss."Roles" ("Id", "Name") FROM stdin;
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: coboss; Owner: postgres
--

COPY coboss."Users" ("Id", "Email", "Password", "Salt", "EmployeeId", "RoleId") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: coboss; Owner: postgres
--

COPY coboss."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240201204231_init	7.0.12
\.


--
-- Name: BusinnessTaskComments_Id_seq; Type: SEQUENCE SET; Schema: coboss; Owner: postgres
--

SELECT pg_catalog.setval('coboss."BusinnessTaskComments_Id_seq"', 1, false);


--
-- Name: BusinnessTaskRealisations_Id_seq; Type: SEQUENCE SET; Schema: coboss; Owner: postgres
--

SELECT pg_catalog.setval('coboss."BusinnessTaskRealisations_Id_seq"', 1, false);


--
-- Name: BusinnessTasks_Id_seq; Type: SEQUENCE SET; Schema: coboss; Owner: postgres
--

SELECT pg_catalog.setval('coboss."BusinnessTasks_Id_seq"', 1, false);


--
-- Name: EmployeeHistories_Id_seq; Type: SEQUENCE SET; Schema: coboss; Owner: postgres
--

SELECT pg_catalog.setval('coboss."EmployeeHistories_Id_seq"', 1, false);


--
-- Name: Employees_Id_seq; Type: SEQUENCE SET; Schema: coboss; Owner: postgres
--

SELECT pg_catalog.setval('coboss."Employees_Id_seq"', 1, false);


--
-- Name: GlobalSettings_Id_seq; Type: SEQUENCE SET; Schema: coboss; Owner: postgres
--

SELECT pg_catalog.setval('coboss."GlobalSettings_Id_seq"', 1, false);


--
-- Name: ObjectCodes_Id_seq; Type: SEQUENCE SET; Schema: coboss; Owner: postgres
--

SELECT pg_catalog.setval('coboss."ObjectCodes_Id_seq"', 1, false);


--
-- Name: Projects_Id_seq; Type: SEQUENCE SET; Schema: coboss; Owner: postgres
--

SELECT pg_catalog.setval('coboss."Projects_Id_seq"', 1, false);


--
-- Name: RefreshTokensData_Id_seq; Type: SEQUENCE SET; Schema: coboss; Owner: postgres
--

SELECT pg_catalog.setval('coboss."RefreshTokensData_Id_seq"', 1, false);


--
-- Name: Roles_Id_seq; Type: SEQUENCE SET; Schema: coboss; Owner: postgres
--

SELECT pg_catalog.setval('coboss."Roles_Id_seq"', 1, false);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: coboss; Owner: postgres
--

SELECT pg_catalog.setval('coboss."Users_Id_seq"', 1, false);


--
-- Name: BusinnessTaskComments PK_BusinnessTaskComments; Type: CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."BusinnessTaskComments"
    ADD CONSTRAINT "PK_BusinnessTaskComments" PRIMARY KEY ("Id");


--
-- Name: BusinnessTaskRealisations PK_BusinnessTaskRealisations; Type: CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."BusinnessTaskRealisations"
    ADD CONSTRAINT "PK_BusinnessTaskRealisations" PRIMARY KEY ("Id");


--
-- Name: BusinnessTasks PK_BusinnessTasks; Type: CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."BusinnessTasks"
    ADD CONSTRAINT "PK_BusinnessTasks" PRIMARY KEY ("Id");


--
-- Name: BusinnessTasksUsers PK_BusinnessTasksUsers; Type: CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."BusinnessTasksUsers"
    ADD CONSTRAINT "PK_BusinnessTasksUsers" PRIMARY KEY ("BusinnessTaskId", "EmployeeId");


--
-- Name: EmployeeHistories PK_EmployeeHistories; Type: CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."EmployeeHistories"
    ADD CONSTRAINT "PK_EmployeeHistories" PRIMARY KEY ("Id");


--
-- Name: Employees PK_Employees; Type: CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."Employees"
    ADD CONSTRAINT "PK_Employees" PRIMARY KEY ("Id");


--
-- Name: GlobalSettings PK_GlobalSettings; Type: CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."GlobalSettings"
    ADD CONSTRAINT "PK_GlobalSettings" PRIMARY KEY ("Id");


--
-- Name: ObjectCodes PK_ObjectCodes; Type: CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."ObjectCodes"
    ADD CONSTRAINT "PK_ObjectCodes" PRIMARY KEY ("Id");


--
-- Name: Projects PK_Projects; Type: CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."Projects"
    ADD CONSTRAINT "PK_Projects" PRIMARY KEY ("Id");


--
-- Name: RefreshTokensData PK_RefreshTokensData; Type: CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."RefreshTokensData"
    ADD CONSTRAINT "PK_RefreshTokensData" PRIMARY KEY ("Id");


--
-- Name: Roles PK_Roles; Type: CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."Roles"
    ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_BusinnessTaskComments_TaskId; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE INDEX "IX_BusinnessTaskComments_TaskId" ON coboss."BusinnessTaskComments" USING btree ("TaskId");


--
-- Name: IX_BusinnessTaskComments_UserId; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE INDEX "IX_BusinnessTaskComments_UserId" ON coboss."BusinnessTaskComments" USING btree ("UserId");


--
-- Name: IX_BusinnessTaskRealisations_EmployeeId; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE INDEX "IX_BusinnessTaskRealisations_EmployeeId" ON coboss."BusinnessTaskRealisations" USING btree ("EmployeeId");


--
-- Name: IX_BusinnessTaskRealisations_TaskId; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE INDEX "IX_BusinnessTaskRealisations_TaskId" ON coboss."BusinnessTaskRealisations" USING btree ("TaskId");


--
-- Name: IX_BusinnessTasksUsers_EmployeeId; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE INDEX "IX_BusinnessTasksUsers_EmployeeId" ON coboss."BusinnessTasksUsers" USING btree ("EmployeeId");


--
-- Name: IX_BusinnessTasks_ProjectId; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE INDEX "IX_BusinnessTasks_ProjectId" ON coboss."BusinnessTasks" USING btree ("ProjectId");


--
-- Name: IX_EmployeeHistories_EmployeeId; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE INDEX "IX_EmployeeHistories_EmployeeId" ON coboss."EmployeeHistories" USING btree ("EmployeeId");


--
-- Name: IX_GlobalSettings_Key; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE UNIQUE INDEX "IX_GlobalSettings_Key" ON coboss."GlobalSettings" USING btree ("Key");


--
-- Name: IX_ObjectCodes_EntityName_CodeNumber; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE UNIQUE INDEX "IX_ObjectCodes_EntityName_CodeNumber" ON coboss."ObjectCodes" USING btree ("EntityName", "CodeNumber");


--
-- Name: IX_Projects_ManagerId; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE INDEX "IX_Projects_ManagerId" ON coboss."Projects" USING btree ("ManagerId");


--
-- Name: IX_Projects_Number; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Projects_Number" ON coboss."Projects" USING btree ("Number");


--
-- Name: IX_RefreshTokensData_Token; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE INDEX "IX_RefreshTokensData_Token" ON coboss."RefreshTokensData" USING btree ("Token");


--
-- Name: IX_RefreshTokensData_UserId; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE INDEX "IX_RefreshTokensData_UserId" ON coboss."RefreshTokensData" USING btree ("UserId");


--
-- Name: IX_Roles_Name; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Roles_Name" ON coboss."Roles" USING btree ("Name");


--
-- Name: IX_Users_Email; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Email" ON coboss."Users" USING btree ("Email");


--
-- Name: IX_Users_EmployeeId; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_EmployeeId" ON coboss."Users" USING btree ("EmployeeId");


--
-- Name: IX_Users_RoleId; Type: INDEX; Schema: coboss; Owner: postgres
--

CREATE INDEX "IX_Users_RoleId" ON coboss."Users" USING btree ("RoleId");


--
-- Name: BusinnessTaskComments FK_BusinnessTaskComments_BusinnessTasks_TaskId; Type: FK CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."BusinnessTaskComments"
    ADD CONSTRAINT "FK_BusinnessTaskComments_BusinnessTasks_TaskId" FOREIGN KEY ("TaskId") REFERENCES coboss."BusinnessTasks"("Id") ON DELETE CASCADE;


--
-- Name: BusinnessTaskComments FK_BusinnessTaskComments_Users_UserId; Type: FK CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."BusinnessTaskComments"
    ADD CONSTRAINT "FK_BusinnessTaskComments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES coboss."Users"("Id") ON DELETE CASCADE;


--
-- Name: BusinnessTaskRealisations FK_BusinnessTaskRealisations_BusinnessTasks_TaskId; Type: FK CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."BusinnessTaskRealisations"
    ADD CONSTRAINT "FK_BusinnessTaskRealisations_BusinnessTasks_TaskId" FOREIGN KEY ("TaskId") REFERENCES coboss."BusinnessTasks"("Id") ON DELETE CASCADE;


--
-- Name: BusinnessTaskRealisations FK_BusinnessTaskRealisations_Employees_EmployeeId; Type: FK CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."BusinnessTaskRealisations"
    ADD CONSTRAINT "FK_BusinnessTaskRealisations_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES coboss."Employees"("Id") ON DELETE CASCADE;


--
-- Name: BusinnessTasksUsers FK_BusinnessTasksUsers_BusinnessTasks_BusinnessTaskId; Type: FK CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."BusinnessTasksUsers"
    ADD CONSTRAINT "FK_BusinnessTasksUsers_BusinnessTasks_BusinnessTaskId" FOREIGN KEY ("BusinnessTaskId") REFERENCES coboss."BusinnessTasks"("Id") ON DELETE CASCADE;


--
-- Name: BusinnessTasksUsers FK_BusinnessTasksUsers_Employees_EmployeeId; Type: FK CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."BusinnessTasksUsers"
    ADD CONSTRAINT "FK_BusinnessTasksUsers_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES coboss."Employees"("Id") ON DELETE CASCADE;


--
-- Name: BusinnessTasks FK_BusinnessTasks_Projects_ProjectId; Type: FK CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."BusinnessTasks"
    ADD CONSTRAINT "FK_BusinnessTasks_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES coboss."Projects"("Id") ON DELETE CASCADE;


--
-- Name: EmployeeHistories FK_EmployeeHistories_Employees_EmployeeId; Type: FK CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."EmployeeHistories"
    ADD CONSTRAINT "FK_EmployeeHistories_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES coboss."Employees"("Id") ON DELETE CASCADE;


--
-- Name: Projects FK_Projects_Employees_ManagerId; Type: FK CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."Projects"
    ADD CONSTRAINT "FK_Projects_Employees_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES coboss."Employees"("Id") ON DELETE CASCADE;


--
-- Name: RefreshTokensData FK_RefreshTokensData_Users_UserId; Type: FK CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."RefreshTokensData"
    ADD CONSTRAINT "FK_RefreshTokensData_Users_UserId" FOREIGN KEY ("UserId") REFERENCES coboss."Users"("Id") ON DELETE CASCADE;


--
-- Name: Users FK_Users_Employees_EmployeeId; Type: FK CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."Users"
    ADD CONSTRAINT "FK_Users_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES coboss."Employees"("Id");


--
-- Name: Users FK_Users_Roles_RoleId; Type: FK CONSTRAINT; Schema: coboss; Owner: postgres
--

ALTER TABLE ONLY coboss."Users"
    ADD CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES coboss."Roles"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

